version: '0.01'
services:
  nutrition-service:
    build: services/nutrition
    container_name: nutrition
    ports:
      - "8080:8080"
  exercise-service:
    build: services/exercise
    container_name: exercise
    ports:
      - "3005:3005"
  user-service:
    build: services/user
    container_name: user
    ports:
      - "8081:8081"